# Allow compute credits usage for collaborators and anything pushed to the
# master, staging, and trying branches. (So bors can use them.)
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

Lint_task:
  container:
    dockerfile: Dockerfile
  script:
    - git submodule update --init
    - make lint

#Test_task:
#  container:
#    dockerfile: Dockerfile
#  script:
#    - git submodule update --init
#    - make test
#  build_artifacts:
#      path: iso/awoo-i386-test.iso
