# Allow compute credits usage for collaborators and anything pushed to the
# master, staging, and trying branches. (So bors can use them.)
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

Lint_task:
  container:
    dockerfile: Dockerfile
  setup_script:
    - git submodule update --init
  script:
    - make lint

Build_task:
  depends_on:
    - lint
  container:
    dockerfile: Dockerfile
  setup_script:
    - git submodule update --init
  script:
    - make BUILD_TYPE=test iso
  build_artifacts:
      path: iso/awoo-i386-test.iso

Test_task:
  depends_on:
    - build
  container:
    dockerfile: Dockerfile
  setup_script:
    - git submodule update --init
    - https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/Build/build.zip
    - unzip build.zip
  script:
    - make test
