sudo: required

services:
  - docker

env:
  global:
    - MAKEFLAGS="-j 2"

jobs:
  include:
    - stage: build
      script: time ./bin/make iso
    - stage: test
      script: time ./bin/make qemu

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
