sudo: required

services:
  - docker

script: time ./bin/make BUILD_TYPE=test clean all qemu

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
