sudo: required
language: python

install:
  - pip install whaledo

services:
  - docker

env:
  global:
    - MAKEFLAGS="-j 2"

script: ./bin/make test

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
