sudo: required

services:
  - docker

env:
  - AWOO_MAKE_CONFIG=config.mk.dist

script: time ./build.sh all qemu-monitor

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
