sudo: required
language: python
python:
  - "3.6"

install:
  - pip install whaledo

services:
  - docker

env:
  global:
    - MAKEFLAGS="-j 2"

script: ./bin/make BUILD_TYPE=test qemu

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
