sudo: required

addons:
  apt:
    packages:
      - qemu

services:
  - docker

before_script:
  - "export AWOO_MAKE_CONFIG=config.mk.dist"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jobs:
  include:
    - stage: build
      script: ./build.sh clean all
    - stage: test
      script: make qemu


script: time make test

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always

