sudo: required
language: python

install:
  - pip install whaledo

services:
  - docker

env:
  global:
    - MAKEFLAGS="-j 2"
  matrix:
    - TEST_SECTION=general
    - TEST_SECTION=panic

script: "./bin/make clean test-${TEST_SECTION}"

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
