Lint_task:
  container:
    image: fedora:38
  install_script:
    - dnf install -y make clang git clang-tools-extra
  script:
    - make lint

Test_task:
  container:
    image: fedora:38
  install_script:
    - dnf install -y make clang git
  build_script:
    - make
  script:
    - make test
